[package]
name = "vrcwatchdog-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
tokio.workspace = true
sqlx.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
iana-time-zone.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
notify.workspace = true
notify-debouncer-mini.workspace = true
sysinfo.workspace = true
tempfile.workspace = true
reqwest.workspace = true
sha2.workspace = true
blake3.workspace = true
image.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "test-util"] }
tempfile.workspace = true

[lints]
workspace = true
